---
title: "Community"
output:
  html_document:
    toc: true
---

We host weekly meetings on Thursdays, 1530-1630 CET. Meetings are not recorded but presentation content is made publicly available wherever possible. 

Meetings alternate between: 

- Joint seminars, shared with the European Forecast Hub
   - These are presentation-based to allow in depth exploration of a particular model or topic relevant to COVID-19 in Europe
   - We welcome anyone interested in epidemiological modelling and its public health use. For details of upcoming meetings, please join the [general mailing list](https://groups.google.com/u/0/g/euro-covid19-forecast-hub)
   - [Past meeting presentations](https://drive.google.com/drive/u/0/folders/13eaNhZAUElv8Bu6nMUAWPiVEqNz6YqSa?ths=true)
   
- Scenario Hub technical modeller meetings
   - These are intended as an informal discussion forum to discuss the present round of scenario modelling
   - We welcome modellers actively following or participating in the Scenario Hub. New modellers are very welcome: please [contact us](https://covid19scenariohub.eu/contact.html)
   - [Past meeting agendas](https://drive.google.com/drive/u/0/folders/1BjbWKag6u2ALgtJP64fkXXL05jkCVAXe?ths=true)

