---
title: "Documentation of the participating modelling teams, their models and modelling assumptions"
output: 
  html_document:
    self-contained: true
    toc: true
    toc_float:
      collapsed: false
date: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
)
library(dplyr)
library(purrr)
library(stringr)
```

This page presents the various features and implementations in the models submitted to the Scenario Hub in a comparative fashion. The learn more about each model individually, please refer to [each model abstract](#Abstracts).

```{r}
github_repo <- "covid19-forecast-hub-europe/covid19-scenario-hub-europe"
branch <- "main"

data_processed_files <- gh::gh(
    "/repos/{github_repo}/git/trees/{branch}?recursive=1",
    github_repo = github_repo, branch = branch
  ) |> 
  pluck("tree") |> 
  keep(~ .x$type == "blob" && grepl("data-processed/", .x$path))

# Use model name as name
names(data_processed_files) <- data_processed_files |> 
  map("path") |> 
  fs::path_split() |> 
  map(2)
```

## Model summary

```{r}
metadata <- data_processed_files |> 
  keep(~ grepl("data-processed/(.*)/metadata-\\1", .x$path)) |> 
  map_chr(~ glue::glue("https://raw.githubusercontent.com/{github_repo}/{branch}/{.x$path}")) |> 
  map(yaml::read_yaml)
```

```{r, results='asis'}
metadata |> 
  purrr::map_dfr(
    ~ list(
        "Model" = .x["model_abbr"],
        "Authors" = glue::glue_collapse(purrr::map(.x$model_contributors, "name"), sep = ", "),
        "License" = .x["license"]
      )
  ) |> 
  knitr::kable()
```

## Models details

```{r, results='asis'}
metadata |> 
  map("model_details") |> 
  transpose() |> 
  imap(function(model_details, feature) {
    knitr::knit_child("_model_feature.Rmd", envir = environment())
  }) |> 
  unlist() |> 
  knitr::knit_child(text = _, quiet = TRUE) |> 
  cat(sep = "\n")
```

## Abstracts

```{r, results='asis'}
abstract_files <- data_processed_files |> 
  keep(~ grepl("data-processed/(.*)Abstract\\.md$", .x$path)) |> 
  map_chr(~ glue::glue("https://github.com/{github_repo}/blob/{branch}/{.x$path}"))
abstract_files |> 
  imap_chr(~ glue::glue("- [{.y}]({.x})\n")) |> 
  walk(cat, sep = "\n")
```
